package com.lionxxw.kqsystem.mapper;

import com.lionxxw.kqsystem.entity.Overtime;
import com.lionxxw.kqsystem.entity.OvertimeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OvertimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_overtime
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int countByExample(OvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_overtime
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int deleteByExample(OvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_overtime
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_overtime
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int insert(Overtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_overtime
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int insertSelective(Overtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_overtime
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    List<Overtime> selectByExample(OvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_overtime
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    Overtime selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_overtime
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") Overtime record, @Param("example") OvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_overtime
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int updateByExample(@Param("record") Overtime record, @Param("example") OvertimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_overtime
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int updateByPrimaryKeySelective(Overtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_overtime
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int updateByPrimaryKey(Overtime record);
}