package com.lionxxw.kqsystem.mapper;

import com.lionxxw.kqsystem.entity.UserOrderResult;
import com.lionxxw.kqsystem.entity.UserOrderResultExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserOrderResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_user_order_dinner_result
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    int countByExample(UserOrderResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_user_order_dinner_result
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    int deleteByExample(UserOrderResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_user_order_dinner_result
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_user_order_dinner_result
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    int insert(UserOrderResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_user_order_dinner_result
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    int insertSelective(UserOrderResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_user_order_dinner_result
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    List<UserOrderResult> selectByExample(UserOrderResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_user_order_dinner_result
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    UserOrderResult selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_user_order_dinner_result
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserOrderResult record, @Param("example") UserOrderResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_user_order_dinner_result
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    int updateByExample(@Param("record") UserOrderResult record, @Param("example") UserOrderResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_user_order_dinner_result
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    int updateByPrimaryKeySelective(UserOrderResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_user_order_dinner_result
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    int updateByPrimaryKey(UserOrderResult record);
}