package com.lionxxw.kqsystem.mapper;

import com.lionxxw.kqsystem.entity.WorkingLog;
import com.lionxxw.kqsystem.entity.WorkingLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WorkingLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_working_log
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int countByExample(WorkingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_working_log
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int deleteByExample(WorkingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_working_log
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_working_log
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int insert(WorkingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_working_log
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int insertSelective(WorkingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_working_log
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    List<WorkingLog> selectByExampleWithBLOBs(WorkingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_working_log
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    List<WorkingLog> selectByExample(WorkingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_working_log
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    WorkingLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_working_log
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") WorkingLog record, @Param("example") WorkingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_working_log
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") WorkingLog record, @Param("example") WorkingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_working_log
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int updateByExample(@Param("record") WorkingLog record, @Param("example") WorkingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_working_log
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int updateByPrimaryKeySelective(WorkingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_working_log
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(WorkingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kq_working_log
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    int updateByPrimaryKey(WorkingLog record);
}