package com.lionxxw.kqsystem.entity;

import java.util.Date;

public class OptionTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner_option_template.id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner_option_template.name
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner_option_template.create_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner_option_template.create_user_id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner_option_template.last_update_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner_option_template.last_update_user_id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private Long lastUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner_option_template.note
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner_option_template.id
     *
     * @return the value of kq_order_dinner_option_template.id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner_option_template.id
     *
     * @param id the value for kq_order_dinner_option_template.id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner_option_template.name
     *
     * @return the value of kq_order_dinner_option_template.name
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner_option_template.name
     *
     * @param name the value for kq_order_dinner_option_template.name
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner_option_template.create_time
     *
     * @return the value of kq_order_dinner_option_template.create_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner_option_template.create_time
     *
     * @param createTime the value for kq_order_dinner_option_template.create_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner_option_template.create_user_id
     *
     * @return the value of kq_order_dinner_option_template.create_user_id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner_option_template.create_user_id
     *
     * @param createUserId the value for kq_order_dinner_option_template.create_user_id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner_option_template.last_update_time
     *
     * @return the value of kq_order_dinner_option_template.last_update_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner_option_template.last_update_time
     *
     * @param lastUpdateTime the value for kq_order_dinner_option_template.last_update_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner_option_template.last_update_user_id
     *
     * @return the value of kq_order_dinner_option_template.last_update_user_id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public Long getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner_option_template.last_update_user_id
     *
     * @param lastUpdateUserId the value for kq_order_dinner_option_template.last_update_user_id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setLastUpdateUserId(Long lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner_option_template.note
     *
     * @return the value of kq_order_dinner_option_template.note
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner_option_template.note
     *
     * @param note the value for kq_order_dinner_option_template.note
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}