package com.lionxxw.kqsystem.entity;

import java.util.Date;

public class OrderDinner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner.id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner.order_date
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner.note
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner.publish_user_id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private Long publishUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner.publish_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner.create_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner.create_user_id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner.state
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner.last_update_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner.end_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner.id
     *
     * @return the value of kq_order_dinner.id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner.id
     *
     * @param id the value for kq_order_dinner.id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner.order_date
     *
     * @return the value of kq_order_dinner.order_date
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner.order_date
     *
     * @param orderDate the value for kq_order_dinner.order_date
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner.note
     *
     * @return the value of kq_order_dinner.note
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner.note
     *
     * @param note the value for kq_order_dinner.note
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner.publish_user_id
     *
     * @return the value of kq_order_dinner.publish_user_id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public Long getPublishUserId() {
        return publishUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner.publish_user_id
     *
     * @param publishUserId the value for kq_order_dinner.publish_user_id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setPublishUserId(Long publishUserId) {
        this.publishUserId = publishUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner.publish_time
     *
     * @return the value of kq_order_dinner.publish_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner.publish_time
     *
     * @param publishTime the value for kq_order_dinner.publish_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner.create_time
     *
     * @return the value of kq_order_dinner.create_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner.create_time
     *
     * @param createTime the value for kq_order_dinner.create_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner.create_user_id
     *
     * @return the value of kq_order_dinner.create_user_id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner.create_user_id
     *
     * @param createUserId the value for kq_order_dinner.create_user_id
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner.state
     *
     * @return the value of kq_order_dinner.state
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner.state
     *
     * @param state the value for kq_order_dinner.state
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner.last_update_time
     *
     * @return the value of kq_order_dinner.last_update_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner.last_update_time
     *
     * @param lastUpdateTime the value for kq_order_dinner.last_update_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner.end_time
     *
     * @return the value of kq_order_dinner.end_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner.end_time
     *
     * @param endTime the value for kq_order_dinner.end_time
     *
     * @mbggenerated Wed Jul 27 14:34:59 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}