package com.lionxxw.kqsystem.entity;

public class OrderDinnerOption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner_options.id
     *
     * @mbggenerated Tue Aug 02 14:52:52 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner_options.order_id
     *
     * @mbggenerated Tue Aug 02 14:52:52 CST 2016
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_order_dinner_options.temp_id
     *
     * @mbggenerated Tue Aug 02 14:52:52 CST 2016
     */
    private Long tempId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner_options.id
     *
     * @return the value of kq_order_dinner_options.id
     *
     * @mbggenerated Tue Aug 02 14:52:52 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner_options.id
     *
     * @param id the value for kq_order_dinner_options.id
     *
     * @mbggenerated Tue Aug 02 14:52:52 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner_options.order_id
     *
     * @return the value of kq_order_dinner_options.order_id
     *
     * @mbggenerated Tue Aug 02 14:52:52 CST 2016
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner_options.order_id
     *
     * @param orderId the value for kq_order_dinner_options.order_id
     *
     * @mbggenerated Tue Aug 02 14:52:52 CST 2016
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_order_dinner_options.temp_id
     *
     * @return the value of kq_order_dinner_options.temp_id
     *
     * @mbggenerated Tue Aug 02 14:52:52 CST 2016
     */
    public Long getTempId() {
        return tempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_order_dinner_options.temp_id
     *
     * @param tempId the value for kq_order_dinner_options.temp_id
     *
     * @mbggenerated Tue Aug 02 14:52:52 CST 2016
     */
    public void setTempId(Long tempId) {
        this.tempId = tempId;
    }
}