package com.lionxxw.kqsystem.entity;

import java.util.Date;

public class Overtime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_overtime.id
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_overtime.user_id
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_overtime.work_date
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private Date workDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_overtime.start_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_overtime.end_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_overtime.is_del
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private Boolean isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_overtime.note
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_overtime.total_house
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private Double totalHouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_overtime.create_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_overtime.last_update_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_overtime.id
     *
     * @return the value of kq_overtime.id
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_overtime.id
     *
     * @param id the value for kq_overtime.id
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_overtime.user_id
     *
     * @return the value of kq_overtime.user_id
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_overtime.user_id
     *
     * @param userId the value for kq_overtime.user_id
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_overtime.work_date
     *
     * @return the value of kq_overtime.work_date
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public Date getWorkDate() {
        return workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_overtime.work_date
     *
     * @param workDate the value for kq_overtime.work_date
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setWorkDate(Date workDate) {
        this.workDate = workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_overtime.start_time
     *
     * @return the value of kq_overtime.start_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_overtime.start_time
     *
     * @param startTime the value for kq_overtime.start_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_overtime.end_time
     *
     * @return the value of kq_overtime.end_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_overtime.end_time
     *
     * @param endTime the value for kq_overtime.end_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_overtime.is_del
     *
     * @return the value of kq_overtime.is_del
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_overtime.is_del
     *
     * @param isDel the value for kq_overtime.is_del
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_overtime.note
     *
     * @return the value of kq_overtime.note
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_overtime.note
     *
     * @param note the value for kq_overtime.note
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_overtime.total_house
     *
     * @return the value of kq_overtime.total_house
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public Double getTotalHouse() {
        return totalHouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_overtime.total_house
     *
     * @param totalHouse the value for kq_overtime.total_house
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setTotalHouse(Double totalHouse) {
        this.totalHouse = totalHouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_overtime.create_time
     *
     * @return the value of kq_overtime.create_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_overtime.create_time
     *
     * @param createTime the value for kq_overtime.create_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_overtime.last_update_time
     *
     * @return the value of kq_overtime.last_update_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_overtime.last_update_time
     *
     * @param lastUpdateTime the value for kq_overtime.last_update_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}