package com.lionxxw.kqsystem.entity;

import java.util.Date;

public class UserOrderResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_user_order_dinner_result.id
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_user_order_dinner_result.user_id
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_user_order_dinner_result.order_id
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_user_order_dinner_result.option_id
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    private Long optionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_user_order_dinner_result.user_cname
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    private String userCname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_user_order_dinner_result.user_ename
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    private String userEname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_user_order_dinner_result.create_time
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_user_order_dinner_result.last_update_time
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_user_order_dinner_result.state
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_user_order_dinner_result.is_append
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    private Boolean isAppend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_user_order_dinner_result.id
     *
     * @return the value of kq_user_order_dinner_result.id
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_user_order_dinner_result.id
     *
     * @param id the value for kq_user_order_dinner_result.id
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_user_order_dinner_result.user_id
     *
     * @return the value of kq_user_order_dinner_result.user_id
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_user_order_dinner_result.user_id
     *
     * @param userId the value for kq_user_order_dinner_result.user_id
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_user_order_dinner_result.order_id
     *
     * @return the value of kq_user_order_dinner_result.order_id
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_user_order_dinner_result.order_id
     *
     * @param orderId the value for kq_user_order_dinner_result.order_id
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_user_order_dinner_result.option_id
     *
     * @return the value of kq_user_order_dinner_result.option_id
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public Long getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_user_order_dinner_result.option_id
     *
     * @param optionId the value for kq_user_order_dinner_result.option_id
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public void setOptionId(Long optionId) {
        this.optionId = optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_user_order_dinner_result.user_cname
     *
     * @return the value of kq_user_order_dinner_result.user_cname
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public String getUserCname() {
        return userCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_user_order_dinner_result.user_cname
     *
     * @param userCname the value for kq_user_order_dinner_result.user_cname
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public void setUserCname(String userCname) {
        this.userCname = userCname == null ? null : userCname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_user_order_dinner_result.user_ename
     *
     * @return the value of kq_user_order_dinner_result.user_ename
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public String getUserEname() {
        return userEname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_user_order_dinner_result.user_ename
     *
     * @param userEname the value for kq_user_order_dinner_result.user_ename
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public void setUserEname(String userEname) {
        this.userEname = userEname == null ? null : userEname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_user_order_dinner_result.create_time
     *
     * @return the value of kq_user_order_dinner_result.create_time
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_user_order_dinner_result.create_time
     *
     * @param createTime the value for kq_user_order_dinner_result.create_time
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_user_order_dinner_result.last_update_time
     *
     * @return the value of kq_user_order_dinner_result.last_update_time
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_user_order_dinner_result.last_update_time
     *
     * @param lastUpdateTime the value for kq_user_order_dinner_result.last_update_time
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_user_order_dinner_result.state
     *
     * @return the value of kq_user_order_dinner_result.state
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_user_order_dinner_result.state
     *
     * @param state the value for kq_user_order_dinner_result.state
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_user_order_dinner_result.is_append
     *
     * @return the value of kq_user_order_dinner_result.is_append
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public Boolean getIsAppend() {
        return isAppend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_user_order_dinner_result.is_append
     *
     * @param isAppend the value for kq_user_order_dinner_result.is_append
     *
     * @mbggenerated Wed Jul 27 14:41:56 CST 2016
     */
    public void setIsAppend(Boolean isAppend) {
        this.isAppend = isAppend;
    }
}