package com.lionxxw.kqsystem.entity;

import java.util.Date;

public class WorkingLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_working_log.id
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_working_log.user_id
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_working_log.work_date
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private Date workDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_working_log.create_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_working_log.last_update_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_working_log.is_del
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private Boolean isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kq_working_log.note
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_working_log.id
     *
     * @return the value of kq_working_log.id
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_working_log.id
     *
     * @param id the value for kq_working_log.id
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_working_log.user_id
     *
     * @return the value of kq_working_log.user_id
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_working_log.user_id
     *
     * @param userId the value for kq_working_log.user_id
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_working_log.work_date
     *
     * @return the value of kq_working_log.work_date
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public Date getWorkDate() {
        return workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_working_log.work_date
     *
     * @param workDate the value for kq_working_log.work_date
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setWorkDate(Date workDate) {
        this.workDate = workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_working_log.create_time
     *
     * @return the value of kq_working_log.create_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_working_log.create_time
     *
     * @param createTime the value for kq_working_log.create_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_working_log.last_update_time
     *
     * @return the value of kq_working_log.last_update_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_working_log.last_update_time
     *
     * @param lastUpdateTime the value for kq_working_log.last_update_time
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_working_log.is_del
     *
     * @return the value of kq_working_log.is_del
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_working_log.is_del
     *
     * @param isDel the value for kq_working_log.is_del
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kq_working_log.note
     *
     * @return the value of kq_working_log.note
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kq_working_log.note
     *
     * @param note the value for kq_working_log.note
     *
     * @mbggenerated Thu Jul 07 15:28:55 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}